### ISSUE TITLE
Nightly/Alpha builds

### ISSUE THREAD

**Issue by joaopedrosgs** [eumario/godot-manager#12]
**Is your feature request related to a problem? Please describe.**
I really wanted to automate the process of downloading the new alpha or nightly Godot 4 builds

**Describe the solution you'd like**
A way to see and download Godot 4 builds, maybe from https://hugo.pro/projects/godot-builds/ or the official ones.

**Describe alternatives you've considered**
Adding custom Godot instances, but this just complicates my workflow

**Comment by eumario** [comment]
This will be part of the v0.2.0 milestone, as I'll be adding Tuxfamily, along with allowing other custom mirrors to be accessible through Godot Manager.

**Comment by joaopedrosgs** [comment]
Cool!
Thanks for the effort you put in on this  =)
