### ISSUE TITLE
internal version not bumped in v0.1.1

### ISSUE THREAD

**Issue by chriba** [eumario/godot-manager#13]
You forgot to bump the version for v0.1.1 inside [libs/Version.cs](https://github.com/eumario/godot-manager/blob/master/libs/Version.cs) which means the version check within the application fails and always wants to update even though it is already the newest version 
Perhaps the release strategy should be improved a little and, for example, a check should be built into the release CI to check whether the version matches the git tag or insert the git tag version into the code :)

**Comment by eumario** [comment]
This is fixed in 0.1.2.  Will be releasing this soon (tm).
