### ISSUE TITLE
Add way to get Location of Godot Editor

### ISSUE THREAD

**Issue by eumario** [eumario/godot-manager#17]
**Is your feature request related to a problem? Please describe.**
Currently, you have to navigate manually to where the version of Godot is installed, in order to get the path to it.

**Describe the solution you'd like**
Add a way to Godot Version Line, to be able to get the location of the installed version to be used in other things, such as Visual Studio Code.

**Comment by GalaxyGamingBoy** [comment]
Unless there is an environment variable for the path of godot, it might be difficult and maybe not time efficient to implement this.
I will look at my environment variables and we will see where to go from there.

**Comment by eumario** [comment]
This is not what I was talking about.  This is more to align with the same feature that is setup with Projects, where you can right click on the Project Line Entry, and select View Files or View Data Folder.  Maybe 3 Menu Items, for View Data Folder, View Installed Location, and Copy Installed Location, so that the location to the Executable can be placed on the Clipboard.
