### ISSUE TITLE
File names are black on a dark background

### ISSUE THREAD

**Issue by Teashrock** [eumario/godot-manager#22]
**Describe the bug**
When browsing through files, their names are displayed in black color while being on a dark background. It's interesting that folder names are displayed with white color.

**To Reproduce**
1. Open embedded file browser.
2. See folder names being white and file names being black.

**Expected behavior**
Any text being displayed corresponding to the current theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/12483854/167863997-5781e92e-bebb-4961-ae43-edefce164eae.png)
![image](https://user-images.githubusercontent.com/12483854/167864136-fd743f12-872d-40c8-888c-309730fd695c.png)

**Complete the Following:**
 - OS: Ubuntu Linux x86_64
 - Version: Focal Fossa 20.04

**Comment by eumario** [comment]
Black is to denote that the files cannot be selected.  The dialog you are showing, is a Browse Folder dialog, not a Browse File dialog.  I will update the theme to ensure these dialogs have proper coloring for the files, being a slate grey to show that they are not selectable.
