### ISSUE TITLE
icon.png missing when creating new project.

### ISSUE THREAD

**Issue by egel557** [eumario/godot-manager#24]
**Describe the bug**
The icon.png file is missing when creating a new project using Godot Manager. This creates an error `load_image: Error opening file 'res://icon.png'` when running a scene.

**To Reproduce**
1. Create a new project using Godot Manager
2. Create new scene and run.
3. There will be an error `load_image: Error opening file 'res://icon.png'`

**Complete the Following:**
 - OS: Windows 10
 - Version 0.1.2

**Comment by eumario** [comment]
This has been fixed by Commit bd41dc47afb95978f28da9c5e5afa2a9c80606c7 and is planned for the 0.1.3 release coming soon(tm).

**Comment by eumario** [comment]
This has been fixed by Commit bd41dc4 and is planned for the 0.1.3 release
coming soon(tm).
