### ISSUE TITLE
Question: Can one create custom templates and use them as the base for new projects?

### ISSUE THREAD

**Issue by MrEvilOnGitHub** [eumario/godot-manager#28]
I would like to know if it is possible to create custom templates which can be selected when creating a new project. I didn't find any option to do so after looking around for a short bit. This would help me with optimizing the creation of new projects

**Comment by eumario** [comment]
Yes, you can create Templates, and have them setup as base projects.  If you goto the Asset Library, and Select the Import Button, Godot Manager will ask you if you would like to import a Template or a Addon.  If you select Template, it will ask you where to find the project.godot, or zip file to import the template.  You can navigate to where your Template is, select the project.godot file, and it will create a Zip file from that directory, and store it in your Cache folder for Godot Manager, and set it up as a Selectable Template in the New Project folder.

**Comment by MrEvilOnGitHub** [comment]
Thank you for the answer
