### ISSUE TITLE
Manually set the order of categories

### ISSUE THREAD

**Issue by RevonZev** [eumario/godot-manager#32]
**Is your feature request related to a problem? Please describe.**
If the user has multiple categories, the user would have to scroll to the category the project is in. For example Demos, Test, and Projects categories; the user would need to scroll to the third (Projects) category. With ordered categories, the user could order the Projects category as the first in the categories and lessen the need to scroll down.

**Describe the solution you'd like**
Add a way to manually order the categories in the category view.

**Describe alternatives you've considered**
Pinned category.

**Comment by eumario** [comment]
Basically, doing like Favorites does in the List View, that is the standard Godot Project Manager design in the Editor
