### ISSUE TITLE
long text project overlap in icon view

### ISSUE THREAD

**Issue by RevonZev** [eumario/godot-manager#33]
**Describe the bug**
Projects with long text/icons overlap with other projects' text/icons.

**To Reproduce**
1. Create a project with a really long name/directory
2. look in the Godot Manager project page icon view

**Expected behavior**
Either warps around or clips the text.

**Screenshots**
![screenshot](https://i.imgur.com/ODKjdBF.png)

**Complete the Following:**
 - OS: Windows 10
 - Version 1.3-release

**Comment by eumario** [comment]
This is weird, it should be clipping the text.  From the looks of it, this should be in Icon View, correct?

**Comment by eumario** [comment]
Nevermind, I didn't read the title of the bug report. lol
