### ISSUE TITLE
Open project after associated Godot version deleted.

### ISSUE THREAD

**Issue by Malcx** [eumario/godot-manager#42]
Platform: Windows 10
GM version: 0.2.0-release

**To Reproduce**
1. Start a clean 1st run of GM
2. During setup wizard, install 3.5.1 stable
3. After setup, add 4.0 beta 2 as a "custom version" (not via tuxfamily)
4. Create a new project "test" with 4.0b2
5. Close everything
6. Start GM
7. Remove 4.0 beta 2
8. Try and open the project "test"

Long pause before GM closes and the project never launches.

**Comment by cromerc** [comment]
A message should be shown telling the user the godot version is not installed. Maybe even ask the user if they want to install it and start the download?

**Comment by Malcx** [comment]
Hmm I don't get that message, but have just tried and found another way to replicate this.

1. Download 4 beta 2 via Tuxfamily
2. Set that as default engine
3. Create a new project called X (using the default engine)
4. Close project X
5. Remove Godot 4 beta 2 but on the screen saying "You only have 1 version of Godot... set as defailt and associate with projects" select [No].
6. Now when trying to open project X Godot Manager hangs, no message is displayed. (Sometimes GM crashes but not every time)

It's a really minor issue and easy to work around, so feel free to make this as non-critical as you can!

**Comment by cromerc** [comment]
I wasn't saying that it does it currently. I was saying what should be done to improve the experience.

**Comment by Malcx** [comment]
Oh sorry my bad for misunderstanding. 
Yeah either that or just ask them which of the installed versions to switch to?
