### ISSUE TITLE
A way for different Godot versions to use the same config folder

### ISSUE THREAD

**Issue by Yagich** [eumario/godot-manager#46]
**Is your feature request related to a problem? Please describe.**
Managing multiple self-contained versions of Godot can be a pain. I need to run 3 different versions of Godot currently, that all need to use different settings: two instances of 3.5.1 for two separate projects, 4.0b4 and 4.0-dev.

**Describe the solution you'd like**
It would be nice to have some kind of "editor groups" system, where multiple installations can re-use one folder with self-contained mode. This would let them share the same configuration/EditorSettings.

**Describe alternatives you've considered**
Currently, I use the system-wide config folder for Godot. I have briefly experimented with having them in self-contained folders, but managing them without a tool like Godot Manager is painful, especially having to keep XDG desktop files updated.

**Additional context**
N/A

**Comment by eumario** [comment]
This is similar to request #45, will group these two together for reference.
