### ISSUE TITLE
News needs a way to abort if it does not timeout

### ISSUE THREAD

**Issue by stl3** [eumario/godot-manager#57]
**Describe the bug**
If you click on News and for some reason you cannot reach the server or it doesn't timeout, you have to either exit the program to stop current request  or to be able to refresh it again.

**To Reproduce**
1. At the main page, click the News button
2. If for some reason there is an issue reaching server or some timeout etc, there is no way to abort the request and have to exit program
**Expected behavior**
Maybe pressing ESC or the refresh button can cancel the current news request if any network related problem arises.

**Screenshots**

**Complete the Following:**
 - OS: Windows10 21H2 19044.2364
 - Version 0.2.1-release

**Additional context**
This isn't really a big problem just a qol really and rather easily resolved.

**Comment by eumario** [comment]
This is an issue with the fact that the Godot Development team are still in the process of re-designing the Website backend, and they have moved news to blog, and Godot Manager doesn't realize this, so I am having to fix it in the next version.

**Comment by shiena** [comment]
[godot-version-manager](https://github.com/noidexe/godot-version-manager) has a news feed, so could it be helpful for implementation?

**Comment by eumario** [comment]
This should be fixed with commit 786811c, I will have to setup a dev environment with Mono and Godot to ensure that this does indeed work.

**Comment by eumario** [comment]
Fixed with commit [fd8949c](https://github.com/eumario/godot-manager/commit/fd8949c120f3c411ea53889156b8d3792cdf6897), Correcting issue with Timeout for download, and new format of News Page (AKA Blog).
