### ISSUE TITLE
4.0 stable crashes when download is (nearly) complete

### ISSUE THREAD

**Issue by MeBadDev** [eumario/godot-manager#61]
**Describe the bug**
When trying to download 4.0 stable, the software crash at 99%.

**To Reproduce**
1. Go to 'download'
2. Click on 'install godot 4'
4. it crashes

**Expected behavior**
It install godot 4.0 stable and add it to avaliable engines

**Screenshots**

**Complete the Following:**
 - OS: Windows
 - Version: Lastest (0.2.1)

**Additional context**
Here is the log:

[godot.log](https://github.com/eumario/godot-manager/files/10869237/godot.log)

**Comment by eumario** [comment]
This is more then likely, a bug with the current Networking subsystem that is being used in 3.5.  As I had to re-work a lot of the code to use Godot's Http Networking Stack, instead of using C#.  This will change in v0.3.0, as I am currently doing a full re-work of the entire code base, to use Godot 4.

**Comment by idortulov** [comment]
I can confirm that the crash is happening.

**Comment by eumario** [comment]
@MeBadDev and @idortulov, can you confirm, if this is happening on a New installation, with no other versions of Godot installed through Godot Manager, or if you have successfully downloaded and installed other versions of Godot through Godot Manager itself please?

**Comment by idortulov** [comment]
It was a brand new installation. I downloaded the release from GitHub Releases. I haven't downloaded any other versions of Godot.

**Comment by eumario** [comment]
@idortulov, Try opening the program, if the first time wizard comes up, complete it without doing an Install of Godot, then try going to the Settings Panel (Gear Icon bottom Left hand corner), and toggle any setting off and on, and then save.  Just need something to update the settings stored on the computer.  Once you have done that, try downloading and installing Godot 4.

**Comment by eumario** [comment]
I have found an issue with Github in 0.2.3 (Which I found with the Re-coding in 0.3.0), that the Godot team has changed the archive file name format for Releases yet again.  So, it isn't properly finding Godot 4 on Github, unless you are on Windows.  (Linux and Mac OS was not properly being found.)  I am correcting the issue in 0.3.0.
