### ISSUE TITLE
Provide godot engine 4 releases

### ISSUE THREAD

**Issue by fire** [eumario/godot-manager#63]
**Is your feature request related to a problem? Please describe.**
I can provide a github actions for build releases on any version.

**Describe the solution you'd like**
Merge github actions for godot-manager to provide automated builds.

**Describe alternatives you've considered**
Using official godot engine releases

Reference https://github.com/protongraph/protongraph/issues/89

**Comment by fire** [comment]
I can probably do a pr later today / this week if there's interest.

**Comment by eumario** [comment]
If you would like to work on something like that, it takes one more things off my plate.  Keep in mind, we don't need a custom build of the Godot Engine.  Standard release will work fine, and the final target is an Executable for Windows, Linux, and Mac OS, using Dotnet 6, for Godot 4.  This is mainly on the godot4 branch, as that is where the work is currently occurring for the next release of Godot Manager.  I'm in the process of getting everything switched over from Godot 3.x to Godot 4.x

**Comment by fire** [comment]
Well that already exists. So one can probably pick on the 2-3 that exist using the official builds.
