### ISSUE TITLE
Godot-manager crashes if you try to create a new project without having imported an old project before

### ISSUE THREAD

**Issue by fmakawa** [eumario/godot-manager#67]
**Describe the bug**
Godot-manager crashes if you try to create a new project without having imported an old project before. If you first import a project it works just fine.

**To Reproduce**
1. Download a new version of godot manager
2. Download a version of Godot
3. Create a new project

**Expected behavior**
It should show the create new project pop to put in the details for the new project

**Complete the Following:**
 - OS:  Windows 11
 - Version 22H2

**Additional context**
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108) - Condition "_first != nullptr" is true.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: cleanup (core/object.cpp:2070) - ObjectDB instances leaked at exit (run with --verbose for details).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417) - Resources still in use at exit (run with --verbose for details).
ERROR: There are still MemoryPool allocs in use at exit!
   at: cleanup (core/pool_vector.cpp:63) - Condition "allocs_used > 0" is true.

**Comment by fmakawa** [comment]
@eumario  seen this yet?

**Comment by eumario** [comment]
This has been fixed with [0620536](https://github.com/eumario/godot-manager/commit/062053632de3286ea947d515726810fc29fdf354), as described in commit log, it is simply crashing cause No Default Engine is setup.  Have edge logic to prevent this from continuing to fail.
