### ISSUE TITLE
Add support for passing commandline arguments to the Godot Engine

### ISSUE THREAD

**Issue by IdoToledano** [eumario/godot-manager#76]
**Is your feature request related to a problem? Please describe.**
I Have a rather low-end device, which doesn't support Vulkan, so I have to use the OpenGL3 rendering driver. As a result, I must execute the engine with the command line argument --rendering-driver opengl3, which prevents me from using the Godot Manager correctly.

**Describe the solution you'd like**
Each engine version installed should have a settings page, where it will be possible to edit it's command line arguments (The settings page might include other settings in the future, if necessary).

An alternative is to use the current settings of each project, and add the requested command line arguments there. Though I am not sure which is more common - changing the command line arguments per project or per Godot version.

**Describe alternatives you've considered**
I was able to launch the project correctly by replacing the Godot version with a bat script that executes the engine with the correct arguments, but it is an ugly solution

**Additional context**
Not relevant

**Comment by IdoToledano** [comment]
By the way, I can create a PR solving this issue when I have time, if needed.

**Comment by eumario** [comment]
It sounds like your using the Godot 4 branch of the project, as the released version, 0.2.3, is set to use OpenGL already.  Godot 0.3.0 will be set for OpenGL rendering to allow the most coverage for usage of the manager itself, before release.

**Comment by IdoToledano** [comment]
I am actually using the 0.2.3 version of the manager (I downloaded the prebuilt version). I wasn't talking about the manager itself using Vulkan by default, but rather engine versions 4+ (that the manager installs). For example, I tried downloading Godot version 4.2-rc 2, and running an example project with it, but I failed because the default driver is Vulkan.

**Comment by eumario** [comment]
Ah, Ok, Now I see what you are talking about.  I will see about adding a Setting to the Project Settings dialog to switch the engine from Vulkan to OpenGL, as it would be a project setting that would be set.

**Comment by IdoToledano** [comment]
Oh, I wasn't talking about the project settings (which now that I think about it, is also lacking the OpenGL renderer option, but that is ). I was talking about the rendering driver that the **editor** itself is using, which is Vulkan by default. To illustrate, upon opening a project, even one that is using the OpenGL rendering driver in the project settings, I get the following, well-known error:

![image](https://github.com/eumario/godot-manager/assets/34353169/89b33fa6-d091-4eba-a63f-68d647b58938)

**Comment by eumario** [comment]
Yes, well, the reason why I was suggesting making it a Project setting, is cause the Editor will use the setting from project.godot to determine which rendering driver to use.  So if you set it to GL Compatible, the editor will automatically launch using the OpenGL3 Renderer, instead of the Vulkan Renderer.  The setting in the project.godot is

[rendering]

renderer/rendering_method="gl_compatibility"
