### ISSUE TITLE
Version sorting Incorrectly sorts versions with only 2 numbers

### ISSUE THREAD

**Issue by Cammymoop** [eumario/godot-manager#80]
Version sorting Incorrectly sorts versions with only 2 numbers

**To Reproduce**
Have versions 4.2-stable and 4.2.1-stable downloaded.
Check Godot Versions page and version selector list. 4.2 is listed above 4.2.1

**Expected behavior**
Sorting should consider X.Y to be the same as X.Y.0
The rest of the details should probably follow SemVer spec too

**Screenshots**
![ApplicationFrameHost_V09cVjHrHi](https://github.com/eumario/godot-manager/assets/6477924/7e1c7d58-8f25-470e-958d-e37237d73458)

OS: Windows
Version: 0.2.3

Related #43

**Comment by eumario** [comment]
I will review your PR and ensure it works, before I merge it into the 0.2.x release.
