### ISSUE TITLE
Allow opening a "News" entry on browser

### ISSUE THREAD

**Issue by bkmeneguello** [eumario/godot-manager#83]
**Is your feature request related to a problem? Please describe.**
When I click any entry on the News panel it doesn't open the related link in the Browser.

**Describe the solution you'd like**
Opening the link in the Browser.

**Describe alternatives you've considered**
Providing the link to the news in a copiable form.

**Comment by eumario** [comment]
It was originally supposed to do this, but for some reason it isn't.  May have gotten messed up.  I will fix this with a sub patch release.
