### ISSUE TITLE
Allow launching a Godot version without creating or opening a project

### ISSUE THREAD

**Issue by bkmeneguello** [eumario/godot-manager#84]
**Is your feature request related to a problem? Please describe.**
In the Godot Versions panel, I want to launch a Godot version.

**Describe the solution you'd like**
Just launching a Godot version.

**Describe alternatives you've considered**
Copying the installation path and opening directly from there.

**Comment by eumario** [comment]
This will be something I will add to the next point release, and 0.3.x release of Godot Manager.
