### ISSUE TITLE
Crash when moving windows with Use System Titlebar disabled on macOS

### ISSUE THREAD

**Issue by shiena** [eumario/godot-manager#89]
**Describe the bug**
Crash when moving windows with `Use System Titlebar` disabled on macOS

**To Reproduce**
1. Disable `Use System Titlebar` on options
2. Save options
3. Grab the top of the window and move it

[crash-report.txt](https://github.com/eumario/godot-manager/files/14662703/crash-report.txt)

**Complete the Following:**
 - OS: macOS 14.4
 - Version: Godot Manager 0.2.3

**Comment by eumario** [comment]
Hello @shiena, Thank you for the crash-report.txt.  Could you look in ~/Library/Application Support/Godot-Manager/logs zip up the files, and attach them, so I can review them to see what is going on.  Thanks.

**Comment by shiena** [comment]
@eumario Please check the log. There were several log files, but they had the same content, so I uploaded only one.
[godot.log](https://github.com/eumario/godot-manager/files/14681893/godot.log)

**Comment by shiena** [comment]
I also attach the log with --verbose option.
[godot.log](https://github.com/eumario/godot-manager/files/14682725/godot.log)

**Comment by shiena** [comment]
`/Users/shiena/Library/Application Support/Godot-Manager/mono/mono_logs/2024-03-21_13.54.22_79808.log`  log file was specified in godot.log, but this file was empty.

**Comment by shiena** [comment]
On macOS it crashes when I set `OS.WindowBorderless` to `true` and update `OS.WindowPosition`.
Maybe it is a bug in Godot Engine.

https://github.com/eumario/godot-manager/blob/master/Scripts/components/Titlebar.cs#L25

**Comment by shiena** [comment]
After further investigation, I found that setting `OS.WindowPostision` to an increased or decreased value causes a crash.
For example, setting `OS.WindowPosition - Vector2.One` will cause a crash.

**Comment by shiena** [comment]
@eumario 
The following changes resolved the issue.
Probably crashes when changing position while moving a window.

```diff
Index: Scripts/components/Titlebar.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Scripts/components/Titlebar.cs b/Scripts/components/Titlebar.cs
--- a/Scripts/components/Titlebar.cs	(revision 368370e0e85b48e318b1f6762fec7749462bbcc0)
+++ b/Scripts/components/Titlebar.cs	(date 1711893982553)
@@ -1,8 +1,10 @@
+using System;
 using Godot;
 using Godot.Sharp.Extras;
 
 public class Titlebar : Control
 {
+    private bool moving = false;
     private bool following = false;
     private Vector2 start_pos = Vector2.Zero;
     public override void _Ready()
@@ -12,8 +14,7 @@
 
     [SignalHandler("gui_input")]
     void OnTitlebar_GuiInput(InputEvent inputEvent) {
-        if (inputEvent is InputEventMouseButton) {
-            var iemb = inputEvent as InputEventMouseButton;
+        if (inputEvent is InputEventMouseButton iemb) {
             if (iemb.ButtonIndex == 1) {
                 following = !following;
                 start_pos = GetLocalMousePosition();
@@ -21,8 +22,10 @@
             }
         }
 
-        if (following) {
+        if (following && !moving) {
+            moving = true;
             OS.WindowPosition = OS.WindowPosition + GetLocalMousePosition() - start_pos;
+            moving = false;
         }
     }
 }
```
