### ISSUE TITLE
Custom directories specified in Setup Wizard silently ignored when given a folder on a different drive.

### ISSUE THREAD

**Issue by willnationsdev** [eumario/godot-manager#90]
Running Windows 10 Pro.

First time install. Setup Wizard appears. Clicking "Next". Suggested to use directories in `C:\Users\Will\AppData\Roaming\...`. Because my C:\ drive is getting pretty full, I opted to create an equivalent folder on a larger E:\ drive at `E:\Programs\AppData\Roaming\` and changed the corresponding paths. After finishing the setup process, I installed the latest Godot version from GitHub, but the various files were all installed to the C:\ drive rather than the E:\ drive.

If installing to an alternate drive is not supported by Godot for some reason, then we should open a bug ticket (if there isn't one already) and add an error message to the setup wizard that disallows paths of that nature. Otherwise, Godot-Manager should save to the directory specified by the user.

Furthermore, I would recommend that validation of whether or not it *can* save to the given directories is performed when the user attempts to move to the next step of the setup wizard. That way the app does not just silently fallback to do it the default way without informing the user.

Edit: Hmmm. I wonder if this happened because the folder I added was marked as "Hidden"? Since it doesn't show up in the file dialog if you try to navigate there manually one folder at a time. Seems like if I enter "AppData" into the path in the FileDialog, it'll navigate me there regardless, so that works fine.

Edit 2: It appears that if you modify the path after the setup wizard completes, the icon to "save changes" or "undo changes" to the settings only appears if you've clicked on the "Browse" button to open a file dialog and selected a path that way. If you just manually change the path text in the LineEdit, there is no GUI update that allows you to save those changes, nor any indication that direct path changes for other LineEdits will be saved if you click "Browse" only for one file path. Like, I can't tell, from the GUI alone, whether it is going to persist whatever changes I make.

**Comment by willnationsdev** [comment]
Ah, just checked the console I ran Godot-Manager from. Lots of errors.

    Mono: Log file is: 'C:/Users/Will/AppData/Roaming/Godot-Manager/mono/mono_logs/2024-03-23_15.15.17_3384.log'
    ERROR: Attempted to convert an unmarshallable managed type to Variant. Name: 'Task`1' Encoding: 21.
       at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1124)
    ERROR: Index p_current = 4 is out of bounds (get_tab_count() = 4).
       at: set_current_tab (scene/gui/tab_container.cpp:593)
    Downloaded 7782 bytes
    Downloaded 8047 bytes
    Downloaded 7968 bytes
    Downloaded 7891 bytes
    Downloaded 1 bytes
    Downloaded 7782 bytes
    Downloaded 23907 bytes

Then a bunch of repetitions of the following error message:

    ERROR: Error calling method from signal 'text_changed': 'Panel(SettingsPanel.cs)::OnGodotInstallLocation': Method not found..
    at: emit_signal (core/object.cpp:1242)

**Comment by eumario** [comment]
Sorry, was working on catching up the Bug List after getting some more free time from my focus on IRL work.  This has been an issue, and I couldn't track it down, till now.  Thanks to the Error message, I now know why it isn't properly updating.  I will get this fixed shortly.
