### ISSUE TITLE
Missing Project right after creating one.

### ISSUE THREAD

**Issue by sebastianoboem** [eumario/godot-manager#95]
**Describe the bug**
Missing Project (on godot default project manager) after trying to open the one i've created.
Some times it closes itself after creating the project (like crashing).

**To Reproduce**
1. Open 'GodotManager'
2. Click on 'New Project'
3. Leave all at 'default' settings (just named the project)
4. Click on 'Create & Edit'

**Expected behavior**
Open Godot project i just created.

**Screenshots**
![Engine Version](https://github.com/eumario/godot-manager/assets/22750871/13860951-8780-47e8-8f2b-13990b3d0ad1)
![New Project](https://github.com/eumario/godot-manager/assets/22750871/5ed3c348-9259-4806-aba9-3a36426090d2)
![Missing Project](https://github.com/eumario/godot-manager/assets/22750871/da2eb3c3-9529-47b4-aa18-d99886b599eb)

**Complete the Following:**
 - OS: Windows 11 Pro - build 23H2
 - Version 0.2.4

**Additional context**
Using Godot 4.2.2

**Comment by eumario** [comment]
Closing, as this is fixed with Commit bcd5065 and ensures that Rendering Engine is properly setup with Escaped Quotes, which would cause the error for the project.
