### ISSUE TITLE
Godot version "Tags" button selector unresponsive

### ISSUE THREAD

**Issue by NoodleSushi** [eumario/godot-manager#98]
**Describe the bug**
The "Tags" button is unresponsive.

**To Reproduce**
1. On sidebar, click "Versions".
2. Click "Tags" button.
3. Toggle "Mono / C#" or choose release types

**Expected behavior**
It should have reflected what I wanted to choose and should have updated the list of available versions based on the tag options.

**Screenshots**
![GodotManager_XMXY8KqzLA](https://github.com/eumario/godot-manager/assets/34954180/0197a40a-5a6f-450a-9542-a0ae425c9053)

**Complete the Following:**
 - OS: Windows 10
 - Version: Godot Manager 0.2.5

**Additional context**
None

**Comment by uweeby** [comment]
I am still having this issue with 0.2.9-release. Tried reinstalling also happening on desktop and laptop. Tried selecting with mouse, space, arrow keys, and enter just for to be extra certain. Also Run As Admin didnt help.

**Comment by 5gTestSubject** [comment]
I am also seeing this issue in 0.2.9-release.

As far as I can tell, this makes this app unusable for C# Godot developers. This is the only menu I can find which will allow me to manage mono versions of the engine.
